# -*- coding: utf-8 -*-
"""Cópia de Cópia de Streamlitapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pNinMBgd0Zj9y3pxjHoudqoiJIG8Ax8r
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np

# -----------------------------------------------------------
# 1. CONFIGURAÇÃO DA PÁGINA
# -----------------------------------------------------------
st.set_page_config(
    page_title="Marketing & Sales — Ciência de Dados I",
    page_icon="📊",
    layout="wide",
)

# -----------------------------------------------------------
# 2. CARREGAMENTO DOS DADOS
# O arquivo CSV deve estar na mesma pasta que o app.py
# -----------------------------------------------------------
@st.cache_data
def carregar_dados():
    df = pd.read_csv("marketing_sales_data.csv")
    df["TV"] = df["TV"].astype("category")
    df["Influencer"] = df["Influencer"].astype("category")
    return df

df = carregar_dados()

VARS_NUM = ["Radio", "Social Media", "Sales"]

# -----------------------------------------------------------
# 3. SIDEBAR — FILTROS GLOBAIS
# -----------------------------------------------------------
st.sidebar.title("🔎 Filtros")
st.sidebar.markdown("Selecione os segmentos que deseja analisar.")

opcoes_tv = ["Todos"] + sorted(df["TV"].cat.categories.tolist())
filtro_tv = st.sidebar.selectbox("Nível de TV", opcoes_tv)

opcoes_inf = ["Todos"] + sorted(df["Influencer"].cat.categories.tolist())
filtro_inf = st.sidebar.selectbox("Tipo de Influencer", opcoes_inf)

df_filtrado = df.copy()
if filtro_tv != "Todos":
    df_filtrado = df_filtrado[df_filtrado["TV"] == filtro_tv]
if filtro_inf != "Todos":
    df_filtrado = df_filtrado[df_filtrado["Influencer"] == filtro_inf]

st.sidebar.markdown("---")
st.sidebar.metric("Registros selecionados", len(df_filtrado))
st.sidebar.metric("Total na base", len(df))

csv = df_filtrado.to_csv(index=False).encode("utf-8")
st.sidebar.download_button(
    label="⬇️ Baixar dados (.csv)",
    data=csv,
    file_name="dados_filtrados.csv",
    mime="text/csv",
)
with st.sidebar:
    st.subheader("Documentação do Projeto")
    # Botão para o Google Colab
    st.link_button(
        "🚀 Abrir Notebook no Google Colab", 
        "https://colab.research.google.com/drive/1EMwTs_kbhG6cUvX2In_vOH6yhXiAWXKX?usp=sharing"
    )
    st.divider() # Adiciona uma linha divisória fina para organizar
    st.subheader("Documentação do Projeto")
    # Botão para o Google Colab
    st.link_button(
        "🚀 Abrir Notebook no Google Colab", 
        "https://colab.research.google.com/drive/1EMwTs_kbhG6cUvX2In_vOH6yhXiAWXKX?usp=sharing"
    )
    
# -----------------------------------------------------------
# 4. CABEÇALHO
# -----------------------------------------------------------
st.title("📊 Marketing & Sales — Análise Exploratória de Dados")
st.markdown(
    "Dashboard interativo desenvolvido para o Trabalho de **Ciência de Dados I**. "
    "Use os filtros na barra lateral para explorar os dados por segmento."
)
st.markdown("---")

# -----------------------------------------------------------
# 5. ABAS DE NAVEGAÇÃO
# -----------------------------------------------------------
(aba_intro, aba_categoricas, aba_numericas, aba_centro,
 aba_dispersao, aba_posicao, aba_boxplot, aba_correlacao,
 aba_scatter, aba_conclusao) = st.tabs([
    "Introdução",
    "Variáveis Categóricas",
    "Variáveis Numéricas",
    "Medidas de Centro",
    "Medidas de Dispersão",
    "Posição Relativa",
    "Boxplots",
    "Correlação & Covariância",
    "Dispersões",
    "Conclusão",
])

# ================================================================
# ABA 1 — INTRODUÇÃO
# ================================================================
with aba_intro:
    st.header("1. Introdução")
    st.markdown("""
Este trabalho tem como objetivo analisar uma base de dados de promoções e investimentos em diferentes
canais de marketing, bem como as vendas resultantes dos investimentos realizados em cada canal.

A base de dados foi adquirida no **Kaggle**, publicada pelo usuário *Yakhyojon*, e é composta por
**527 observações** e **5 variáveis**:

| Variável | Tipo | Descrição |
|---|---|---|
| **TV** | Ordinal (categórica) | Nível de investimento em televisão: Low, Medium ou High |
| **Radio** | Contínua (float64) | Volume em milhões de USD investidos em rádio |
| **Social Media** | Contínua (float64) | Volume em milhões de USD investidos em redes sociais |
| **Influencer** | Nominal (categórica) | Tipo de influenciador contratado: Nano, Micro, Macro ou Mega |
| **Sales** | Contínua (float64) | Volume de vendas gerado pelos investimentos (em milhões de USD) |
    """)

    st.markdown("---")
    st.subheader("2. Exploração Inicial dos Dados")

    col1, col2, col3 = st.columns(3)
    col1.metric("Linhas (observações)", df.shape[0])
    col2.metric("Colunas (variáveis)", df.shape[1])
    col3.metric("Valores nulos", int(df.isnull().sum().sum()))

    st.markdown("**Primeiras 10 linhas da base:**")
    st.dataframe(df.head(10), use_container_width=True)

    st.markdown("**Últimas 10 linhas da base:**")
    st.dataframe(df.tail(10), use_container_width=True)

    st.markdown("**Tipos de variáveis:**")
    tipos = df.dtypes.reset_index()
    tipos.columns = ["Variável", "Tipo"]
    st.dataframe(tipos, use_container_width=True, hide_index=True)

    st.markdown("**Verificação de valores nulos:**")
    nulos = df.isnull().sum().reset_index()
    nulos.columns = ["Variável", "Valores Nulos"]
    st.dataframe(nulos, use_container_width=True, hide_index=True)

    n_dup = int(df.duplicated().sum())
    st.metric("Linhas duplicadas", n_dup)

    st.info(
        "✅ **Qualidade dos dados:** Nenhuma coluna apresenta valores nulos e nenhuma linha duplicada "
        "foi encontrada. Cada registro representa uma observação única, garantindo que a análise "
        "não será distorcida por repetições ou dados ausentes."
    )

    st.markdown("""
**Interpretação dos tipos:**

As variáveis **TV** e **Influencer** são do tipo *object* (texto), indicando dados categóricos.
TV representa o nível de investimento em televisão (Low, Medium ou High), enquanto Influencer
identifica o tipo de influenciador contratado (Nano, Micro, Macro ou Mega).

As variáveis **Radio**, **Social Media** e **Sales** são do tipo *float64*, correspondendo a variáveis
numéricas contínuas. Essas variáveis podem assumir valores decimais e são adequadas para análises
estatísticas como média, mediana, desvio padrão e correlação.
    """)

# ================================================================
# ABA 2 — VARIÁVEIS CATEGÓRICAS
# ================================================================
with aba_categoricas:
    st.header("3. Análise de Variáveis Categóricas")
    st.markdown(
        "Frequências absolutas, relativas e acumuladas para as variáveis categóricas "
        "**TV** e **Influencer** no segmento selecionado."
    )

    def tabela_freq(serie, nome):
        freq = serie.value_counts().reset_index()
        freq.columns = [nome, "Frequência Absoluta"]
        total = freq["Frequência Absoluta"].sum()
        freq["Frequência Relativa"] = (freq["Frequência Absoluta"] / total).round(6)
        freq["Frequência Acumulada"] = freq["Frequência Relativa"].cumsum().round(6)
        freq["Frequência Relativa (%)"] = (freq["Frequência Relativa"] * 100).round(2)
        freq["Frequência Acumulada (%)"] = (freq["Frequência Acumulada"] * 100).round(2)
        return freq[[nome, "Frequência Absoluta", "Frequência Relativa", "Frequência Acumulada"]]

    col_a, col_b = st.columns(2)

    with col_a:
        st.subheader("3.1 Variável Influencer")
        tb_inf = tabela_freq(df_filtrado["Influencer"], "Influencer")
        st.dataframe(tb_inf, use_container_width=True, hide_index=True)

        fig_inf = px.bar(
            tb_inf, x="Influencer", y="Frequência Absoluta",
            title="Frequência por tipo de Influencer",
            color="Influencer",
            color_discrete_sequence=px.colors.qualitative.Set2,
        )
        fig_inf.update_layout(showlegend=False)
        st.plotly_chart(fig_inf, use_container_width=True)

    with col_b:
        st.subheader("3.2 Variável TV")
        tb_tv = tabela_freq(df_filtrado["TV"], "TV")
        st.dataframe(tb_tv, use_container_width=True, hide_index=True)

        fig_tv = px.bar(
            tb_tv, x="TV", y="Frequência Absoluta",
            title="Frequência por nível de TV",
            color="TV",
            color_discrete_sequence=px.colors.qualitative.Pastel,
        )
        fig_tv.update_layout(showlegend=False)
        st.plotly_chart(fig_tv, use_container_width=True)

    st.markdown("---")
    st.markdown("""
**Interpretação — Influencer:**
A distribuição ficou bem equilibrada entre as quatro categorias, sem nenhum grupo dominante.
Nano e Micro lideram com pequena vantagem (≈ 27% e ≈ 26%), enquanto Macro tem a menor presença
(≈ 22%). A diferença entre o maior (Nano, 157) e o menor (Macro, 127) é de apenas 30 registros,
indicando uma base diversificada em relação ao tipo de influenciador. Nenhuma categoria ultrapassa
28% da base, confirmando o equilíbrio observado.

**Interpretação — TV:**
Medium e Low são os níveis mais frequentes, com 205 e 201 registros respectivamente, enquanto High
aparece menos (166 registros ≈ 29%). Os níveis Medium e Low juntos correspondem a quase 71% dos
registros. Vale ter isso em mente nas análises seguintes — conclusões sobre alto investimento em TV
estarão baseadas em uma amostra proporcionalmente menor.
    """)

# ================================================================
# ABA 3 — VARIÁVEIS NUMÉRICAS
# ================================================================
with aba_numericas:
    st.header("4. Análise de Variáveis Numéricas")
    st.markdown(
        "Estatísticas descritivas fundamentais das variáveis numéricas: "
        "**Radio**, **Social Media** e **Sales**."
    )

    # Média, mediana, máx, mín
    radio = df_filtrado["Radio"]
    sm = df_filtrado["Social Media"]
    sales = df_filtrado["Sales"]

    dados_resumo = {
        "Variável": ["Rádio", "Social Media", "Sales"],
        "Média (USD)": [radio.mean(), sm.mean(), sales.mean()],
        "Mediana (USD)": [radio.median(), sm.median(), sales.median()],
        "Máximo (USD)": [radio.max(), sm.max(), sales.max()],
        "Mínimo (USD)": [radio.min(), sm.min(), sales.min()],
    }
    tb_resumo = pd.DataFrame(dados_resumo)
    st.dataframe(
        tb_resumo.style.format({
            "Média (USD)": "{:.6f}",
            "Mediana (USD)": "{:.6f}",
            "Máximo (USD)": "{:.6f}",
            "Mínimo (USD)": "{:.6f}",
        }),
        use_container_width=True,
        hide_index=True,
    )

    st.markdown("**Estatísticas descritivas completas (describe):**")
    desc = df_filtrado[VARS_NUM].describe().T
    desc["CV (%)"] = (desc["std"] / desc["mean"] * 100).round(2)
    desc.columns = ["n", "Média", "Desvio Padrão", "Mín", "Q1", "Mediana", "Q3", "Máx", "CV (%)"]
    st.dataframe(desc.style.format("{:.4f}"), use_container_width=True)

    st.markdown("---")
    st.markdown("""
**Interpretação:**

- **Rádio:** média ≈ USD 17,52 milhões e mediana ≈ USD 17,15 milhões. O canal possui um "piso"
  de investimento relevante, sugerindo que funciona como canal de manutenção constante,
  recebendo recursos independentemente do escopo da campanha.

- **Social Media:** média ≈ USD 3,33 milhões e mediana ≈ USD 3,15 milhões. É o único canal com
  valor mínimo praticamente zero, indicando a existência de períodos ou campanhas sem qualquer
  aporte digital.

- **Sales:** média ≈ USD 189,30 milhões e mediana ≈ USD 184,01 milhões. A proximidade entre média
  e mediana indica distribuição relativamente equilibrada, sem forte influência de valores extremos.

A amplitude observada entre os valores mínimos e máximos, especialmente na variável de vendas,
evidencia uma considerável variabilidade nos resultados obtidos.
    """)

# ================================================================
# ABA 4 — MEDIDAS DE CENTRO
# ================================================================
with aba_centro:
    st.header("5. Medidas de Centro")
    st.markdown(
        "Média e mediana das variáveis numéricas segmentadas por **nível de TV** e "
        "**tipo de Influencer**, permitindo avaliar como cada variável se comporta "
        "conforme as decisões estratégicas da empresa."
    )

    st.subheader("5.1 Vendas (Sales) por segmento")
    col1, col2 = st.columns(2)

    with col1:
        st.markdown("**Por nível de TV**")
        vendas_tv = df_filtrado.groupby("TV", observed=True)["Sales"].agg(["mean", "median"]).round(6)
        vendas_tv.columns = ["Média", "Mediana"]
        st.dataframe(vendas_tv, use_container_width=True)

    with col2:
        st.markdown("**Por tipo de Influencer**")
        vendas_inf = df_filtrado.groupby("Influencer", observed=True)["Sales"].agg(["mean", "median"]).round(6)
        vendas_inf.columns = ["Média", "Mediana"]
        st.dataframe(vendas_inf, use_container_width=True)

    st.subheader("5.2 Rádio (Radio) por segmento")
    col3, col4 = st.columns(2)

    with col3:
        st.markdown("**Por nível de TV**")
        radio_tv = df_filtrado.groupby("TV", observed=True)["Radio"].agg(["mean", "median"]).round(6)
        radio_tv.columns = ["Média", "Mediana"]
        st.dataframe(radio_tv, use_container_width=True)

    with col4:
        st.markdown("**Por tipo de Influencer**")
        radio_inf = df_filtrado.groupby("Influencer", observed=True)["Radio"].agg(["mean", "median"]).round(6)
        radio_inf.columns = ["Média", "Mediana"]
        st.dataframe(radio_inf, use_container_width=True)

    st.subheader("5.3 Social Media por segmento")
    col5, col6 = st.columns(2)

    with col5:
        st.markdown("**Por nível de TV**")
        sm_tv = df_filtrado.groupby("TV", observed=True)["Social Media"].agg(["mean", "median"]).round(6)
        sm_tv.columns = ["Média", "Mediana"]
        st.dataframe(sm_tv, use_container_width=True)

    with col6:
        st.markdown("**Por tipo de Influencer**")
        sm_inf = df_filtrado.groupby("Influencer", observed=True)["Social Media"].agg(["mean", "median"]).round(6)
        sm_inf.columns = ["Média", "Mediana"]
        st.dataframe(sm_inf, use_container_width=True)

    st.markdown("---")
    st.markdown("""
**Interpretação:**

O investimento em TV é o grande motor das vendas. Campanhas com alto investimento em televisão
geram mais que o **triplo** do faturamento em comparação com as de baixo investimento (High ≈ USD 300 mi
vs. Low ≈ USD 91 mi em média).

O tipo de influenciador contratado tem um impacto bem menor e mais uniforme nos resultados.
Um dado curioso: influenciadores da categoria **Nano** chegam a ter uma mediana de vendas
ligeiramente maior que os da categoria **Mega**, sugerindo que perfis menores e focados em nichos
específicos podem ser tão eficientes na conversão quanto os mais famosos.

Em todos os agrupamentos, a média e a mediana ficaram com valores muito próximos, indicando que
a base de dados é consistente e não possui valores extremos (outliers) capazes de distorcer
a realidade de algum segmento.
    """)

# ================================================================
# ABA 5 — MEDIDAS DE DISPERSÃO
# ================================================================
with aba_dispersao:
    st.header("6. Medidas de Dispersão")
    st.markdown(
        "Desvio padrão e Coeficiente de Variação (CV) para as variáveis numéricas, "
        "permitindo comparar a volatilidade relativa de cada canal."
    )

    vars_num_filt = df_filtrado[VARS_NUM]
    desvio = vars_num_filt.std()
    media = vars_num_filt.mean()
    cv = (desvio / media * 100).round(4)

    tb_disp = pd.DataFrame({
        "Variável": VARS_NUM,
        "Desvio Padrão (USD)": desvio.values,
        "Coeficiente de Variação (%)": cv.values,
    })
    st.dataframe(
        tb_disp.style.format({
            "Desvio Padrão (USD)": "{:.6f}",
            "Coeficiente de Variação (%)": "{:.4f}",
        }),
        use_container_width=True,
        hide_index=True,
    )

    fig_cv = px.bar(
        tb_disp,
        x="Variável",
        y="Coeficiente de Variação (%)",
        color="Variável",
        title="Coeficiente de Variação por variável numérica",
        color_discrete_sequence=px.colors.qualitative.Set2,
    )
    fig_cv.update_layout(showlegend=False)
    st.plotly_chart(fig_cv, use_container_width=True)

    st.markdown("---")
    st.markdown("""
**Interpretação:**

- **Sales** apresenta o maior desvio padrão absoluto (≈ USD 89,87 mi), o que é natural pela sua
  escala. Porém, é a **variável percentualmente mais estável** (CV ≈ 47,5%), significando que,
  proporcionalmente, o faturamento oscila de forma mais controlada.

- **Social Media** é a variável mais volátil da operação: embora seu desvio padrão absoluto seja
  pequeno (≈ USD 2,24 mi), seu **CV é o mais alto** (≈ 67,1%), comprovando que o orçamento para
  redes sociais sofre mudanças drásticas entre as campanhas — variando agressivamente entre aportes
  muito baixos (ou zerados) e muito altos.

- **Rádio** ocupa a posição intermediária (CV ≈ 53%), confirmando ser um canal com variações
  orçamentárias frequentes, mas um pouco menos radicais que as do ambiente digital.
    """)

# ================================================================
# ABA 6 — MEDIDAS DE POSIÇÃO RELATIVA
# ================================================================
with aba_posicao:
    st.header("7. Medidas de Posição Relativa")
    st.markdown("Quartis (Q1, mediana, Q3), mínimo e máximo para cada variável numérica.")

    st.subheader("7.1 Quartis gerais")
    est_geral = df_filtrado[VARS_NUM].describe().loc[["min", "25%", "50%", "75%", "max"]]
    est_geral.index = ["Mínimo", "Q1 (25%)", "Q2 — Mediana (50%)", "Q3 (75%)", "Máximo"]
    st.dataframe(est_geral.style.format("{:.6f}"), use_container_width=True)

    st.subheader("7.2 Quartis por nível de TV")
    for var in VARS_NUM:
        st.markdown(f"**{var}**")
        qt_tv = (
            df_filtrado.groupby("TV", observed=True)[var]
            .describe()[["min", "25%", "50%", "75%", "max"]]
            .rename(columns={"min": "Mín", "25%": "Q1", "50%": "Mediana", "75%": "Q3", "max": "Máx"})
        )
        st.dataframe(qt_tv.style.format("{:.4f}"), use_container_width=True)

    st.subheader("7.3 Quartis por tipo de Influencer")
    for var in VARS_NUM:
        st.markdown(f"**{var}**")
        qt_inf = (
            df_filtrado.groupby("Influencer", observed=True)[var]
            .describe()[["min", "25%", "50%", "75%", "max"]]
            .rename(columns={"min": "Mín", "25%": "Q1", "50%": "Mediana", "75%": "Q3", "max": "Máx"})
        )
        st.dataframe(qt_inf.style.format("{:.4f}"), use_container_width=True)

# ================================================================
# ABA 7 — BOXPLOTS
# ================================================================
with aba_boxplot:
    st.header("7.1 Visualização Gráfica — Boxplots")
    st.markdown(
        "O boxplot mostra Q1, mediana, Q3 e outliers. "
        "Passe o mouse sobre os pontos para ver os valores exatos."
    )

    var_box = st.selectbox("Variável a analisar", VARS_NUM, key="var_box")
    agrupar_por = st.radio(
        "Agrupar por", ["TV", "Influencer"],
        horizontal=True, key="group_box"
    )

    fig_box = px.box(
        df_filtrado,
        x=agrupar_por,
        y=var_box,
        color=agrupar_por,
        points="outliers",
        title=f"Distribuição de {var_box} por {agrupar_por}",
        labels={var_box: var_box, agrupar_por: agrupar_por},
        color_discrete_sequence=px.colors.qualitative.Set2,
    )
    fig_box.update_layout(showlegend=False)
    st.plotly_chart(fig_box, use_container_width=True)

    st.markdown("---")
    st.subheader("Interpretações fixas dos boxplots")

    st.markdown("**Boxplots com variável Influencer:**")
    st.markdown("""
- **Sales por Influencer:** As quatro caixas são praticamente idênticas em tamanho, posição e
  mediana. O tipo de influenciador, sozinho, não diferencia os resultados de vendas.
- **Social Media por Influencer:** Macro tem a caixa posicionada um pouco mais abaixo, com mediana
  mais próxima do Q1, indicando que campanhas com esse tipo de influenciador tendem a investir menos
  em redes sociais. Mega e Nano apresentam caixas ligeiramente mais altas.
- **Radio por Influencer:** As quatro caixas são quase idênticas, indicando que o tipo de
  influenciador não está associado a diferenças no investimento em rádio. Todos os grupos
  apresentam outliers acima da haste superior.
    """)

    st.markdown("**Boxplots com variável TV:**")
    st.markdown("""
- **Sales por TV:** Diferença mais evidente entre grupos. High tem caixa compacta com resultados
  concentrados entre 270–350 mi. Low tem a caixa mais larga, com resultados altamente variáveis.
  Medium tem os resultados mais estáveis (caixa mais baixa e compacta).
- **Social Media por TV:** High TV investe consideravelmente mais, com mediana mais alta e caixa
  variável no patamar elevado. Isso sugere uma possível estratégia combinada: quem investe muito
  em TV também tende a investir mais em redes sociais.
- **Radio por TV:** Padrão semelhante ao de Social Media. High TV apresenta investimentos em rádio
  mais elevados e consistentes. Low TV apresenta a maior variabilidade.
    """)

    st.markdown("---")
    st.subheader("Histograma de frequências")
    var_hist = st.selectbox("Variável", VARS_NUM, key="var_hist")
    n_bins = st.slider("Número de barras", min_value=10, max_value=60, value=30, step=5)

    fig_hist = px.histogram(
        df_filtrado,
        x=var_hist,
        nbins=n_bins,
        color="TV",
        barmode="overlay",
        opacity=0.7,
        title=f"Histograma de {var_hist}",
        color_discrete_sequence=px.colors.qualitative.Set2,
    )
    st.plotly_chart(fig_hist, use_container_width=True)

# ================================================================
# ABA 8 — CORRELAÇÃO & COVARIÂNCIA
# ================================================================
with aba_correlacao:
    st.header("8. Análise de Correlação e Covariância")

    # 8.1 Correlação de Pearson
    st.subheader("8.1 Matriz de Correlação de Pearson")
    st.caption(
        "Valores próximos de 1 indicam forte correlação positiva; "
        "próximos de -1, negativa; próximos de 0, ausência de correlação linear."
    )

    corr = df_filtrado[VARS_NUM].corr(method="pearson")
    st.dataframe(corr.style.format("{:.6f}"), use_container_width=True)

    fig_corr = px.imshow(
        corr,
        text_auto=".2f",
        color_continuous_scale="RdBu_r",
        zmin=-1, zmax=1,
        title="Correlação de Pearson",
        aspect="auto",
    )
    st.plotly_chart(fig_corr, use_container_width=True)

    corr_sales = corr["Sales"].drop("Sales").abs()
    var_mais_corr = corr_sales.idxmax()
    valor_corr = corr["Sales"][var_mais_corr]
    st.info(
        f"A variável com maior correlação com **Sales** no segmento selecionado "
        f"é **{var_mais_corr}** com um coeficiente de **{valor_corr:.4f}**."
    )

    st.markdown("""
**Interpretação:**

A matriz de correlação de Pearson confirma numericamente o que os gráficos indicavam.
Existe correlação positiva entre os investimentos e as vendas. O **Rádio** apresenta a maior
correlação com Sales (≈ 0,858), consolidando-se como o investimento com maior força de associação
linear com o faturamento. **Social Media** apresenta correlação mais fraca (≈ 0,542).
    """)

    st.markdown("---")

    # 8.2 Covariância
    st.subheader("8.2 Matriz de Covariância")
    st.caption(
        "Covariância positiva indica que as variáveis tendem a aumentar juntas; "
        "negativa indica relação inversa."
    )

    cov = df_filtrado[VARS_NUM].cov()
    st.dataframe(cov.style.format("{:.4f}"), use_container_width=True)

    st.markdown("""
**Interpretação:**

Todas as covariâncias são positivas, confirmando que as variáveis tendem a aumentar
independentemente da combinação escolhida. A relação entre **Radio e Sales** é a que apresenta
a covariância mais alta, reforçando a forte associação linear entre esses dois canais.
    """)

    st.markdown("---")

    # 8.3 Índice de Sharpe
    st.subheader("8.3 Índice de Sharpe")
    st.caption(
        "Razão entre a média e o desvio padrão de cada variável — "
        "quanto maior, mais estável é o retorno em relação à variação."
    )

    sharpe = (df_filtrado[VARS_NUM].mean() / df_filtrado[VARS_NUM].std()).round(4)
    sharpe_df = sharpe.reset_index()
    sharpe_df.columns = ["Variável", "Índice de Sharpe"]

    st.dataframe(sharpe_df, use_container_width=True, hide_index=True)

    fig_sharpe = px.bar(
        sharpe_df,
        x="Variável",
        y="Índice de Sharpe",
        color="Variável",
        title="Índice de Sharpe por variável",
        color_discrete_sequence=px.colors.qualitative.Set2,
        text_auto=".3f",
    )
    fig_sharpe.update_layout(showlegend=False)
    st.plotly_chart(fig_sharpe, use_container_width=True)

    sharpe_sales = float(sharpe["Sales"])
    st.markdown(f"""
**Interpretação:**

O Índice de Sharpe calculado para a variável de vendas foi de **{sharpe_sales:.2f}**.
No contexto de negócios e finanças, valores acima de 1 são considerados positivos,
e um índice superior a 2 indica um cenário de **excelente eficiência**. Isso significa que,
para cada unidade de "risco" (volatilidade e incerteza nos resultados), a empresa consegue
gerar {sharpe_sales:.2f} unidades de faturamento. A estratégia atual de marketing não apenas
traz retornos altos, mas faz isso de forma muito consistente e previsível.
    """)

# ================================================================
# ABA 9 — GRÁFICOS DE DISPERSÃO
# ================================================================
with aba_scatter:
    st.header("8.4 Gráficos de Dispersão")
    st.markdown(
        "Visualize a relação entre pares de variáveis numéricas. "
        "A linha de tendência (OLS) mostra a direção da relação linear."
    )

    # Gráfico fixo: Radio vs Sales
    st.subheader("Radio vs Sales")
    fig_rs = px.scatter(
        df_filtrado,
        x="Radio",
        y="Sales",
        trendline="ols",
        trendline_scope="overall",
        opacity=0.6,
        title="Dispersão: Investimento em Rádio vs Vendas",
        labels={"Radio": "Investimento em Rádio (USD)", "Sales": "Vendas (USD)"},
        color_discrete_sequence=["#4C72B0"],
    )
    st.plotly_chart(fig_rs, use_container_width=True)

    st.markdown("""
**Interpretação:**
O gráfico evidencia uma **clara correlação positiva** entre o investimento em Rádio e o retorno em
Vendas. A nuvem de pontos segue uma tendência ascendente bastante definida: à medida que a verba
destinada ao rádio aumenta, o volume de faturamento também cresce de maneira proporcional.
As campanhas com os maiores aportes em rádio (acima de USD 30 mi) foram as que consistentemente
alcançaram o topo dos resultados de vendas (acima de USD 300 mi). O rádio atua como uma
**alavanca direta** para o crescimento do faturamento.
    """)

    st.markdown("---")

    # Gráfico fixo: Social Media vs Sales
    st.subheader("Social Media vs Sales")
    fig_ss = px.scatter(
        df_filtrado,
        x="Social Media",
        y="Sales",
        trendline="ols",
        trendline_scope="overall",
        opacity=0.6,
        title="Dispersão: Investimento em Social Media vs Vendas",
        labels={"Social Media": "Investimento em Social Media (USD)", "Sales": "Vendas (USD)"},
        color_discrete_sequence=["#DD8452"],
    )
    st.plotly_chart(fig_ss, use_container_width=True)

    st.markdown("""
**Interpretação:**
Ao contrário do Rádio, o gráfico para Redes Sociais apresenta uma nuvem de pontos muito mais
espalhada e menos definida. A correlação entre as duas variáveis é visivelmente mais fraca.
Nota-se um grande acúmulo de pontos no canto esquerdo: campanhas com investimentos baixíssimos em
redes sociais (abaixo de USD 2 mi) alcançando resultados extremamente variados, desde faturamentos
muito baixos até picos superiores a USD 300 mi.

O investimento financeiro em Social Media, **de forma isolada**, não é um bom preditor para o
sucesso das vendas. O retorno final depende muito mais de outros fatores da campanha, como o
orçamento principal direcionado à TV e a eficácia do influenciador contratado.
    """)

    st.markdown("---")

    # Gráfico interativo
    st.subheader("Dispersão interativa — escolha os eixos")
    col_x, col_y, col_cor = st.columns(3)

    with col_x:
        eixo_x = st.selectbox("Eixo X", VARS_NUM, index=0, key="eixo_x")
    with col_y:
        eixo_y = st.selectbox("Eixo Y", VARS_NUM, index=2, key="eixo_y")
    with col_cor:
        cor_por = st.selectbox("Colorir por", ["TV", "Influencer"], key="cor_por")

    fig_scatter = px.scatter(
        df_filtrado,
        x=eixo_x,
        y=eixo_y,
        color=cor_por,
        trendline="ols",
        trendline_scope="overall",
        title=f"{eixo_x} vs {eixo_y} — colorido por {cor_por}",
        opacity=0.65,
        color_discrete_sequence=px.colors.qualitative.Set2,
    )
    st.plotly_chart(fig_scatter, use_container_width=True)

    st.markdown("---")
    st.subheader("Scatter matrix — todos os pares de variáveis")
    st.caption("Visão completa de todas as combinações de variáveis numéricas.")

    fig_matrix = px.scatter_matrix(
        df_filtrado,
        dimensions=VARS_NUM,
        color=cor_por,
        opacity=0.5,
        color_discrete_sequence=px.colors.qualitative.Set2,
        title="Scatter Matrix — todas as variáveis",
    )
    fig_matrix.update_traces(diagonal_visible=False)
    st.plotly_chart(fig_matrix, use_container_width=True)

# ================================================================
# ABA 10 — CONCLUSÃO
# ================================================================
with aba_conclusao:
    st.header("9. Conclusão")

    st.markdown("""
A análise exploratória da base de dados evidencia que os **investimentos em mídia tradicional**
são os principais motores do faturamento da empresa.

---

### 📺 Televisão — o grande balizador dos resultados

A Televisão atua como a grande balizadora dos resultados. Campanhas com alto investimento nesse
canal chegam a **triplicar as vendas** em comparação com as de baixo orçamento
(média de ≈ USD 300 mi vs. ≈ USD 91 mi). A tomada de decisão estratégica deve garantir que
a espinha dorsal do orçamento permaneça ancorada nesse canal.

---

### 📻 Rádio — alavanca financeira segura e previsível

O Rádio demonstrou a **fortíssima correlação positiva** com as vendas (r ≈ 0,86), consolidando-se
como uma alavanca financeira segura. Os gráficos de dispersão confirmam que maiores aportes em
rádio resultam consistentemente em maiores vendas. É também o canal com o "piso" de investimento
mais elevado, funcionando como mídia de manutenção constante.

---

### 📱 Social Media — canal de apoio e volátil

O ecossistema digital apresentou comportamento mais volátil e complementar. O investimento em
Redes Sociais possui o **maior Coeficiente de Variação** (≈ 67%) e, de forma isolada, a correlação
mais fraca com o resultado final (r ≈ 0,54). O canal atua muito mais como mídia de apoio,
amplificando o efeito de campanhas robustas em TV e Rádio.

---

### 🤳 Influencers — nicho supera o alcance massivo

Os dados revelaram que o alcance massivo **não é sinônimo de maior retorno**: influenciadores
da categoria **Nano** geraram medianas de vendas equivalentes ou até superiores aos perfis **Mega**.
Para a gestão, isso representa uma excelente oportunidade de otimização de custos e maximização
do ROI — direcionando a verba para perfis de nicho que convertem com alta eficiência, sem a
necessidade de arcar com cachês inflacionados.

---

### 📈 Índice de Sharpe — eficiência da operação

O Índice de Sharpe de vendas ≈ **2,11** indica que a estratégia atual entrega resultados não
apenas altos, mas de forma **muito consistente e previsível**, compensando com folga as variações
naturais das campanhas.

---

### 🎯 Recomendações estratégicas

1. **Manter e priorizar** o investimento em TV como principal alocação orçamentária.
2. **Continuar investindo em Rádio** como canal complementar de alto retorno previsível.
3. **Otimizar Social Media** com foco em qualidade de campanha, não apenas volume financeiro.
4. **Privilegiar Nano e Micro influenciadores** para maximizar o ROI, reduzindo custos com
   perfis Mega sem comprometer os resultados.
    """)

# ================================================================
# RODAPÉ
# ================================================================
st.markdown("---")
st.caption(
    "Ciência de Dados I · Trabalho Acadêmico · "
    "Dashboard desenvolvido com **Streamlit** e **Plotly**"
)
